### PR TITLE
Prox sensor

### PR DESCRIPTION
**Pull request by GregAC**

### CODE REVIEW

**Comment by GregAC** [comment]
Recreated version of https://github.com/lowRISC/sonata-software/pull/14 as some bit of github infrastructure fell over so CI wasn't running and merging wasn't possible.

**Comment by GregAC** [comment]
Bypassing CI, checked and fixed locally and it's not getting a runner.

**Comment by GregAC** [comment]
Unfortunately github is refusing to merge 'Merge attempt failed'

So will leave it for now try again tomorrow!

**Comment by nbdd0121** [comment]
Change runs-on in .github/workflows/ci.yml from 23.11 to 24.05 should fix the issue. I fixed the sonata-system repo but forgot to change this repo.

**Comment by GregAC** [comment]
Merging on the basis of the previous review (https://github.com/lowRISC/sonata-software/pull/14)

**Pull request merged**
